import type { PlatformFormat, Product } from "./types";

export const industries = [
  "General Local Business",
  "Plumber",
  "Electrician",
  "Locksmith",
  "HVAC",
  "Realtor",
  "Cleaning Company",
  "Dog Groomer",
  "Hair Salon",
  "Med Spa",
  "Dentist",
  "Massage Clinic",
  "Auto Repair Shop",
  "Contractor",
  "Painter",
  "Drywaller",
  "Tile Installer",
  "Mason",
  "Landscaper",
  "Fitness Studio",
  "Restaurant",
  "Cafe",
  "Hotel",
  "Other",
];

export const tones = ["Professional", "Friendly", "Playful", "Premium", "Bold", "Urgent but not pushy"];
export const visualStyles = [
  "Dark blue tech glow",
  "Clean corporate blue",
  "Premium black and blue",
  "Light modern business",
  "Industry-specific realistic photo",
];
export const ctas = [
  "Auto",
  "Book Your Discovery Call Today",
  "See How It Works",
  "Ask Us About This System",
  "Find Out How We Can Help",
  "Start Capturing More Leads",
  "Get More Booked Appointments",
];
export const aspectRatios = ["1:1", "4:5", "9:16", "1.91:1", "3:4"];
export const expressions = ["Happy", "Confident", "Focused", "Irritated", "Angry"];

export const formats: PlatformFormat[] = [
  { id: "facebook-feed-post", platform: "Facebook", name: "Feed Post", aspectRatio: "4:5", resolution: "1080x1350" },
  { id: "facebook-feed-ad", platform: "Facebook", name: "Feed Ad", aspectRatio: "1:1", resolution: "1080x1080" },
  { id: "facebook-stories-reels", platform: "Facebook", name: "Stories/Reels", aspectRatio: "9:16", resolution: "1080x1920" },
  { id: "facebook-link-ad", platform: "Facebook", name: "Link Ad", aspectRatio: "1.91:1", resolution: "1200x628" },
  { id: "instagram-standard-post", platform: "Instagram", name: "Standard Post", aspectRatio: "4:5", resolution: "1080x1350" },
  { id: "instagram-grid-post", platform: "Instagram", name: "Grid Post", aspectRatio: "3:4", resolution: "1080x1440" },
  { id: "instagram-feed-ad", platform: "Instagram", name: "Feed Ad", aspectRatio: "4:5", resolution: "1080x1350" },
  { id: "instagram-stories-reels", platform: "Instagram", name: "Stories/Reels", aspectRatio: "9:16", resolution: "1080x1920" },
];

export const products: Product[] = [
  {
    id: "ai_receptionist",
    name: "AI Receptionist",
    positioning:
      "A 24/7 AI phone receptionist for local businesses. Answers calls and messages, captures lead details, qualifies inquiries, handles common questions, and helps book appointments.",
    hooks: [
      "Busy With Clients?",
      "Stop Letting Calls Go To Voicemail",
      "Your 24/7 AI Receptionist Is Always On",
      "Answer Every Call - Even When You Can't",
      "Missed Calls Shouldn't Mean Missed Leads",
    ],
    painPoints: [
      "Business owners miss calls while serving clients.",
      "New leads often call once and move on if nobody answers.",
      "Voicemail creates delay and friction.",
      "Staff are too busy to answer every call consistently.",
      "After-hours calls often go unanswered.",
      "Customers ask the same basic questions repeatedly.",
      "Appointment requests get delayed or forgotten.",
      "Leads are not always captured or organized properly.",
    ],
    solutionLines: [
      "Your AI Receptionist answers the calls you can't.",
      "Capture more inquiries while you stay focused on your work.",
      "Let AI handle common questions, lead details, and booking requests.",
      "Give callers a faster response without relying on voicemail.",
      "Help turn more missed calls into real conversations.",
    ],
    featureBubbles: [
      "Answers Calls",
      "Works 24/7",
      "Books Appointments",
      "Captures Leads",
      "Qualifies Inquiries",
      "Custom Call Flow",
      "Calendar Booking",
      "Fast Response",
      "No Voicemail Delay",
      "Handles FAQs",
    ],
    ctas: ["Book Your Discovery Call", "See How AI Receptionist Works", "Ask Us About This System", "Start Capturing More Calls", "Find Out How We Can Help"],
    visualDirection:
      "Image of a busy business owner, contractor, service provider, or receptionist occupied with a client or task while a phone call comes in. The AI Receptionist handles the call while the person keeps working.",
    imagePromptLogic:
      "Realistic vertical photo of a business owner or service provider actively working with a client or on a job while a phone notification/call is visible nearby. Person looks professional and busy. Apply selected facial expression naturally. Leave clean space for headline and feature bubbles.",
  },
  {
    id: "smart_website",
    name: "Smart Website",
    positioning:
      "A professional business website with smart AI features. Modern, mobile-friendly, captures leads, answers questions, helps book appointments.",
    hooks: ["Your Website Should Work After Hours", "More Than A Website", "Turn Visitors Into Booked Appointments", "Is Your Website Leaking Leads?", "A Smarter Website For Local Business"],
    painPoints: [
      "The current website does not bring in enough leads.",
      "Visitors leave without calling, booking, or filling out a form.",
      "The website looks outdated or unprofessional.",
      "The mobile experience is weak.",
      "Calls to action are unclear.",
      "Customers have questions but no one answers them instantly.",
      "The website does not capture useful lead information.",
      "The business owner does not know how many opportunities are being missed.",
    ],
    solutionLines: [
      "Turn your website into a smarter lead capture system.",
      "Help visitors get answers and take action faster.",
      "Give your business a website that can capture leads and support bookings.",
      "Make your website more useful for customers and easier to act on.",
      "Add AI-powered support to help turn visitors into conversations.",
    ],
    featureBubbles: ["Mobile Friendly", "AI Website Chat", "Lead Capture", "Calendar Booking", "Clear CTAs", "SEO-Ready", "Fast Loading", "Smart Website", "24/7 Responses", "Built To Convert"],
    ctas: ["Get Your Smart Website", "Book Your Discovery Call", "See How It Works", "Ask About Smart Websites", "Start Capturing More Leads"],
    visualDirection: "Modern business owner reviewing a website, a laptop/tablet with clean interface elements, or a service business owner seeing a lead notification.",
    imagePromptLogic:
      "Realistic vertical image of a local business owner using a laptop or tablet in a clean modern workspace, with subtle blue tech glow elements around the device. Apply selected facial expression naturally. Leave clear space for ad text overlays.",
  },
  {
    id: "social_ai_assistant",
    name: "Social Media AI Lead Assistant",
    positioning:
      "An AI assistant that helps capture and respond to social media leads from platforms like Facebook and Instagram. Answers questions, qualifies leads, collects details, and helps book appointments from social media lead conversations.",
    hooks: ["Stop Letting Social Media Leads Go Cold", "Turn Social Media Leads Into Bookings", "Your Social Media Leads Need Faster Replies", "Don't Let Your Social Platforms Leak Leads", "Capture Social Media Leads Without Living On Your Phone"],
    painPoints: [
      "DMs sit unanswered too long.",
      "Leads lose interest before the business replies.",
      "Business owners are too busy to monitor messages all day.",
      "Social media platform leads are hard to keep organized.",
      "Basic questions get repeated over and over.",
      "Potential customers ask about services but never get moved to booking.",
      "Social media platform traffic does not always turn into appointments.",
      "Follow-ups are inconsistent.",
    ],
    solutionLines: [
      "Help social media leads get faster replies.",
      "Turn social media platform leads into organized lead conversations.",
      "Let AI answer common questions and guide people toward booking.",
      "Keep social media leads from going cold.",
      "Spend less time manually replying to the same questions.",
    ],
    featureBubbles: ["Social Media Lead Capture", "Lead Qualification", "Books Appointments", "Fast Follow-Up", "Platform Lead Capture", "Works 24/7", "Answers FAQs", "Keeps Leads Warm", "Less Manual Replying", "Brand-Matched Voice"],
    ctas: ["Book Your Discovery Call", "See Social Media Lead Capture In Action", "Ask About Social Media AI", "Start Capturing Social Leads", "Turn Social Media Leads Into Bookings"],
    visualDirection: "Business owner reviewing social media leads from Instagram/Facebook-style platforms, phone with lead notification graphics, or a service provider busy with work while social media lead opportunities come in.",
    imagePromptLogic:
      "Realistic vertical photo of a local business owner holding a smartphone with message notification-style graphics, looking busy but professional. Modern workspace or business setting. Apply selected facial expression naturally. Leave clean space for ad text.",
  },
  {
    id: "customer_refresh",
    name: "Customer Refresh Campaign",
    positioning:
      "One-time customer reactivation campaign. Reconnects with old leads, past customers, dormant contacts using polite automated outreach, list cleanup, and booking logic.",
    hooks: ["Your Old Customer List Has Untapped Opportunity", "Wake Up Past Customers", "Turn Old Contacts Into New Conversations", "Your Database Is Not Dead", "Reconnect With Customers Who Already Know You"],
    painPoints: [
      "Past customers have not been contacted in a long time.",
      "Old leads are sitting in a list doing nothing.",
      "The business owner does not have time to manually follow up.",
      "Customer lists are messy or outdated.",
      "Follow-up messages feel awkward to write.",
      "Past customers forget to come back.",
      "Businesses focus only on new leads while ignoring existing contacts.",
      "There is no clear system for re-engagement.",
    ],
    solutionLines: [
      "Reconnect with people who already know your business.",
      "Turn dormant contacts into fresh conversations.",
      "Use polite outreach to bring past customers back into the pipeline.",
      "Refresh your old customer list without manual chasing.",
      "Help restart conversations with leads and customers already in your database.",
    ],
    featureBubbles: ["Past Customer Outreach", "List Cleanup", "Gentle Follow-Up", "Booking Logic", "Reply Tracking", "Reconnect Campaign", "Existing Contacts", "Brand-Safe Messaging", "Automated Outreach", "Warm Leads"],
    ctas: ["Ask About Customer Refresh", "Book Your Discovery Call", "Reconnect With Past Customers", "See How This Campaign Works", "Start Refreshing Your Customer List"],
    visualDirection: "Business owner looking at a quiet booking calendar, an old customer list, a CRM dashboard, or a phone with reactivation reply notifications. Communicates hidden opportunity.",
    imagePromptLogic:
      "Realistic vertical image of a local business owner at a desk reviewing an old customer list or booking calendar, thoughtful but optimistic unless another expression is selected. Subtle phone notification elements. Leave room for ad copy.",
  },
  {
    id: "review_growth_campaign",
    name: "Google Review Growth Campaign",
    positioning:
      "One-time review growth campaign. Follows up with past and current customers to politely request honest Google reviews.",
    hooks: ["Happy Customers Should Become Google Reviews", "Most Happy Customers Forget To Leave A Review", "Make Reviews Easier To Collect", "Turn Good Service Into More Trust", "Ask For Reviews The Right Way"],
    painPoints: [
      "Happy customers leave without writing a review.",
      "The business owner feels awkward asking for reviews.",
      "Review requests are inconsistent.",
      "Customers forget once they leave.",
      "The Google review link is hard for customers to find.",
      "Staff forget to ask.",
      "The business has fewer reviews than it should.",
      "Competitors look more trusted online because they have more visible reviews.",
    ],
    solutionLines: [
      "Make it easier for happy customers to leave a review.",
      "Give customers a direct path to your Google review page.",
      "Follow up politely without making review requests awkward.",
      "Help turn great service into stronger local trust.",
      "Create a simple review request process your customers can follow.",
    ],
    featureBubbles: ["Review Requests", "Google Review Link", "Gentle Follow-Up", "No Pressure", "Easy For Customers", "Past Customer Outreach", "Trust Builder", "Local Reputation", "Automated Flow", "Honest Feedback"],
    ctas: ["Ask About Review Growth", "Book Your Discovery Call", "Start Collecting More Reviews", "See How Review Growth Works", "Build More Local Trust"],
    visualDirection: "Happy customer leaving a business, a business owner checking Google reviews, or a clean front desk/customer interaction.",
    imagePromptLogic:
      "Realistic vertical image of a happy customer at a local business counter or service location, holding a smartphone as if leaving feedback. Natural and trustworthy. Apply selected expression naturally. Leave clear space for ad copy.",
  },
  {
    id: "review_growth_ongoing",
    name: "Google Review Growth Ongoing Automation",
    positioning: "Ongoing review automation that asks each new customer for a Google review after a service, visit, or purchase.",
    hooks: ["Every New Customer Gets Asked", "Stop Forgetting To Ask For Reviews", "Put Review Requests On Autopilot", "Make Google Review Follow-Up Consistent", "Build Trust One Customer At A Time"],
    painPoints: [
      "Staff forget to ask for reviews.",
      "Review requests happen randomly.",
      "Customers are happy but never prompted.",
      "The owner has to remember to follow up manually.",
      "Review growth slows down because there is no system.",
      "The business misses chances to build trust after each completed job.",
      "Review asking feels inconsistent or awkward.",
      "Customers do not know where to go to leave feedback.",
    ],
    solutionLines: [
      "Put review requests into a simple automated flow.",
      "Make review follow-up more consistent after each customer visit.",
      "Give customers an easy direct link to leave feedback.",
      "Stop relying on memory to ask for reviews.",
      "Build review follow-up into your normal customer process.",
    ],
    featureBubbles: ["Automated Requests", "Direct Google Link", "Consistent Follow-Up", "Easy Customer Flow", "Ongoing Automation", "No Manual Chasing", "Trust Builder", "Review Workflow", "After-Service Follow-Up", "Local Reputation"],
    ctas: ["Automate Your Review Requests", "Book Your Discovery Call", "Ask About Ongoing Reviews", "See How Review Automation Works", "Start Building Local Trust"],
    visualDirection: "Completed service moment, satisfied customer, or business owner reviewing recent feedback. Communicates consistent review follow-up.",
    imagePromptLogic:
      "Realistic vertical image of a satisfied customer after a completed service, with a subtle smartphone review action. Professional, local, trustworthy. Apply selected expression naturally. Leave room for text overlay.",
  },
  {
    id: "nfc_review_station",
    name: "NFC Google Review Tap Station",
    positioning: "Physical NFC/QR review stand at a front desk, counter, or service location. Customers tap or scan and go directly to the business's Google review page.",
    hooks: ["One Tap To Your Google Reviews", "Make Reviews Easy At The Counter", "Turn Happy Customers Into Reviews", "Stop Letting Great Feedback Walk Out", "Tap. Review. Build Trust."],
    painPoints: [
      "Customers leave happy but never leave a review.",
      "Staff forget to ask at checkout.",
      "Customers do not want to search for the business online.",
      "Review links are hard to share in person.",
      "The business misses review opportunities at the moment customers are satisfied.",
      "Asking for reviews feels awkward.",
      "The front desk has no simple review tool.",
      "Customers need a frictionless way to leave feedback.",
    ],
    solutionLines: [
      "Give customers a one-tap path to your Google review page.",
      "Make review asking easier at the counter.",
      "Turn happy in-person visits into online trust.",
      "Reduce friction with NFC tap and QR scan options.",
      "Make it simple for customers to leave feedback before they forget.",
    ],
    featureBubbles: ["One-Tap Reviews", "QR + NFC", "No App Needed", "Front Desk Ready", "Google Review Link", "Easy Setup", "Local Trust", "Review Growth", "Tap To Review", "Simple Customer Flow"],
    ctas: ["Get Your Review Tap Station", "Ask About NFC Review Tools", "Start Collecting Reviews", "See How Tap-To-Review Works", "Book Your Discovery Call"],
    visualDirection: "Front desk, counter, checkout area, or reception space with a small tap-to-review stand and a customer holding a phone nearby.",
    imagePromptLogic:
      "Realistic vertical image of a clean local business counter with a modern NFC/QR review stand and a customer holding a smartphone near it. Apply selected expression naturally if a person is visible. Leave clear space for ad copy. Avoid fake readable brand names or random text.",
  },
  {
    id: "nfc_business_card",
    name: "NFC Digital Business Card",
    positioning: "Wallet-ready NFC digital business card. Share vCard/contact details with one tap or QR scan.",
    hooks: ["Your Business Card Should Do More", "Stop Handing Out Paper That Gets Lost", "One Tap Shares Your Contact Info", "Modern Networking Starts With A Tap", "Make Every Introduction Easier"],
    painPoints: [
      "Paper cards get lost or thrown away.",
      "People mistype phone numbers or emails.",
      "LinkedIn connections are forgotten.",
      "Professionals run out of printed cards.",
      "Updating printed cards is costly and annoying.",
      "Contact sharing at events can feel clumsy.",
      "People do not save the contact after meeting.",
      "The business wants a more modern first impression.",
    ],
    solutionLines: [
      "Share your contact details with one tap.",
      "Help people save your information instantly.",
      "Replace throwaway paper cards with a reusable contact tool.",
      "Make networking faster, cleaner, and more modern.",
      "Give every introduction a more professional follow-up path.",
    ],
    featureBubbles: ["Tap To Share", "Saves vCard", "Wallet Ready", "QR + NFC", "No App Needed", "LinkedIn Link", "Easy Updates", "Modern Networking", "Reusable Card", "Professional Contact"],
    ctas: ["Get Your Digital Business Card", "Ask About NFC Business Cards", "Upgrade Your Networking", "See How Tap-To-Share Works", "Book Your Discovery Call"],
    visualDirection:
      "Two clearly different professionals facing each other in a modern office, exchanging contact info. Person #1 on the left holds a small white printed business card in landscape orientation. Person #2 on the right holds a tall black smartphone vertically close to their own torso. Use realistic object proportions and keep them consistent in the same depth plane: the business card is a thin 3.5 inch by 2 inch horizontal card with a 1.75:1 width-to-height ratio; the card is about 1.2 to 1.3 times as wide as the phone, and the phone is about 2.7 to 3 times as tall as the card. The phone should look like a normal iPhone-sized object, not an oversized foreground prop. The business card should look like a normal physical business card, not a square card, folded paper, postcard, tablet, or screen. Person #2 should hold the phone with their own clearly visible hand or both hands, with shoulder, upper arm, bent elbow, forearm, wrist, cuff/sleeve, and hand all visible in one natural unbroken line leading to the phone. The phone hand must not enter from outside the frame and must not look like a third person's hand. The two objects are held a few inches apart as if about to NFC-tap. Avoid detached hands, mystery hands, extra hands, cropped-in foreground hands, oversized phone, tiny phone, oversized card, square card, two cards, two phones, blank phones, Wi-Fi icons, or Bluetooth icons.",
    imagePromptLogic:
      "Photorealistic vertical advertising photo, exactly two people only, in a modern office, coworking space, clinic, or hotel lobby. Person #1 stands on the left and holds a small white printed business card between thumb and forefinger. The card is landscape orientation, flat and thin, exactly like a standard business card: 3.5 inches wide by 2 inches tall, with a strict 1.75:1 width-to-height ratio. In the image, the business card should be about 1.2 to 1.3 times wider than the phone screen, while the phone should be about 2.7 to 3 times taller than the business card. The card and phone should be in a similar depth plane so perspective does not make either object look strangely huge or tiny. The card must not look like a square card, coaster, folded paper, postcard, tablet, screen, or mini phone. Person #2 stands on the right and holds a modern black smartphone vertically close to Person #2's own torso. The phone is realistic smartphone size, not an oversized foreground prop. Critical composition rule: the smartphone must be held by Person #2's own visible hand or both hands, and the image must show a continuous, anatomically clear connection from Person #2's shoulder to upper arm to bent elbow to forearm to wrist to hand to phone. The sleeve or cuff must be visible and connected to Person #2's body. The phone must not be held by a cropped foreground hand. Do not crop the phone hand, wrist, forearm, elbow, or sleeve at the frame edge. Do not show any disembodied hand, third-person hand, assistant hand, photographer hand, floating hand, or hand entering from outside the frame. The card and phone are clearly different objects, held near each other in the center as if mid-NFC tap. Premium lighting, shallow depth of field, clean background, quiet upper-left negative space reserved for the real logo overlay. Hard avoid: detached or mystery phone hand, oversized foreground phone hand, extra hands, oversized phone, tiny phone, oversized business card, square business card, postcard-sized card, both people holding same object, two phones, two cards, card rendered as phone/screen/coaster, phone rendered as paper card, black or locked phone screen, Wi-Fi or Bluetooth symbols.",
  },
  {
    id: "nfc_contact_station",
    name: "NFC Business Contact Tap Station",
    positioning: "Front-desk/countertop NFC/QR tap station. Customers save the business's contact, location, phone, and booking link to their phone.",
    hooks: ["Keep Your Business In Their Pocket", "Stop Losing Customers After They Leave", "One Tap Saves Your Business Info", "Make It Easy For Customers To Come Back", "Turn Foot Traffic Into Future Bookings"],
    painPoints: [
      "Customers leave without saving the business contact info.",
      "People forget the business name or phone number later.",
      "Customers intend to book again but do not follow through.",
      "Staff repeat contact details over and over.",
      "Business cards or brochures get lost.",
      "Booking links are not easy to access in person.",
      "Walk-in traffic does not always become repeat business.",
      "Customers have to search online later.",
    ],
    solutionLines: [
      "Let customers save your business info with one tap.",
      "Keep your phone, map, and booking link in their pocket.",
      "Make it easier for customers to return or book later.",
      "Turn front desk traffic into saved contacts.",
      "Reduce friction after the customer leaves.",
    ],
    featureBubbles: ["Save Contact", "Booking Link", "Map Location", "QR + NFC", "Front Desk Ready", "One-Tap Contact", "No App Needed", "Repeat Visits", "Always In Pocket", "Easy Customer Flow"],
    ctas: ["Get Your Contact Tap Station", "Ask About Business Tap Tools", "Make It Easier To Rebook", "See How Contact Tap Works", "Book Your Discovery Call"],
    visualDirection: "Front desk, clinic counter, salon counter, office reception, or retail checkout with a customer tapping a phone near a contact station.",
    imagePromptLogic:
      "Realistic vertical image of a customer at a front desk tapping a smartphone near a modern NFC/QR contact station. Clean, local, practical, professional. Apply selected expression naturally if a person is visible. Leave room for ad copy.",
  },
  {
    id: "nfc_social_station",
    name: "NFC Social Media Follow Station",
    positioning: "Physical NFC/QR social follow station. Makes it easy for customers to open and follow the business's social profiles.",
    hooks: ["Turn Customers Into Followers", "Make Social Follows Easy", "One Tap Opens Your Socials", "Stop Letting Customers Leave Without Following", "Grow Your Audience At The Counter"],
    painPoints: [
      "Customers leave without following the business.",
      "People forget to search for the business on social media.",
      "Social handles are hard to spell or remember.",
      "Staff do not always ask customers to follow.",
      "Printed signs with usernames are easy to ignore.",
      "The business wants more local followers.",
      "Happy customers are not being moved into the social audience.",
      "Social growth is inconsistent.",
    ],
    solutionLines: [
      "Make it easier for customers to follow your social pages.",
      "Turn foot traffic into local followers.",
      "Give customers a one-tap path to your socials.",
      "Reduce searching, typing, and confusion.",
      "Keep customers connected after they leave.",
    ],
    featureBubbles: ["Tap To Follow", "QR + NFC", "All Social Links", "No Searching", "Local Followers", "Front Desk Ready", "Simple Customer Flow", "Grow Audience", "Social Connection", "No App Needed"],
    ctas: ["Get Your Social Follow Station", "Ask About Social Tap Tools", "Grow Your Local Audience", "See How Social Tap Works", "Book Your Discovery Call"],
    visualDirection:
      "Customer at a cafe, salon, front desk, studio, clinic, or retail counter tapping a phone near a physical social media follow card. The follow card should look like the provided Facebook or Instagram NFC/QR reference cards: a small rounded rectangular countertop card with platform branding at the top, tap-phone NFC instruction, and QR code area. Use the reference card as the source for the physical object style, not a generic sign.",
    imagePromptLogic:
      "Realistic vertical image of a customer tapping a smartphone near a clean social media follow card at a local business counter. Use one of the supplied reference assets as the exact style reference for the card: Facebook follow card or Instagram follow card. The card should be visible as a physical NFC/QR countertop card, with realistic thickness, rounded corners, platform color, NFC/tap-phone area, and QR code zone. Do not turn it into a poster, phone screen, tablet, paper flyer, or floating UI graphic. Modern and friendly. Apply selected expression naturally if a person is visible. Leave space for ad text.",
    assetReferences: [
      "Facebook follow card reference: https://booked-ai-ad-prompt-builder.vercel.app/brand/social-follow/facebook-follow-card.png",
      "Instagram follow card reference: https://booked-ai-ad-prompt-builder.vercel.app/brand/social-follow/instagram-follow-card.png",
    ],
  },
  {
    id: "guest_wifi",
    name: "Guest Wi-Fi Connect Station",
    positioning: "Physical QR Wi-Fi connect station. Guests connect to Wi-Fi quickly without typing a password or asking staff.",
    hooks: ["Guest Wi-Fi Without The Password Hassle", "Let Customers Connect In Seconds", "Stop Repeating The Wi-Fi Password", "Scan To Connect", "Make Guest Wi-Fi Easier"],
    painPoints: [
      "Customers constantly ask staff for the Wi-Fi password.",
      "Written passwords get outdated or hard to read.",
      "Guests mistype the password.",
      "Staff are interrupted by the same question repeatedly.",
      "Customers expect quick and easy Wi-Fi.",
      "The business wants a more modern guest experience.",
      "Wi-Fi access is clunky or frustrating.",
      "The business is missing a simple branded touchpoint.",
    ],
    solutionLines: [
      "Let guests connect by scanning a QR code.",
      "Reduce repeated Wi-Fi questions at the counter.",
      "Make Wi-Fi access easier for customers and staff.",
      "Remove password typing friction.",
      "Create a cleaner guest experience.",
    ],
    featureBubbles: ["Scan-To-Connect Wi-Fi", "No Password Typing", "QR Code Access", "Staff Time Saver", "Guest Friendly", "Branded Portal", "Optional Email Capture", "Easy Setup", "Fast Connection", "No App Needed"],
    ctas: ["Get Your Wi-Fi Connect Station", "Ask About Guest Wi-Fi Tools", "Make Wi-Fi Easier", "See How QR Wi-Fi Works", "Book Your Discovery Call"],
    visualDirection: "Customer in a cafe, clinic, salon, hotel lobby, or waiting room connecting to Wi-Fi by scanning a QR code on a small Wi-Fi connect sign.",
    imagePromptLogic:
      "Realistic vertical image of a guest or customer scanning a QR code on a small Wi-Fi connect sign in a cafe, clinic, salon, or waiting area. The sign should communicate QR-based Wi-Fi access only. Do not show NFC icons, tap-to-connect language, NFC waves, or phone-tapping gestures. Clean, bright, professional. Apply selected expression naturally if a person is visible. Leave space for ad copy.",
  },
];
